import { Game } from "../types/Game";
import { GameCategory } from "../types/Game";

export const games: Game[] = [
  {
    id: "1",
    name: "Starburst",
    provider: "NetEnt",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "2",
    name: "Mega Moolah",
    provider: "Microgaming",
    image: "/slot.jpg",
    category: GameCategory.TABLE,
    isFavorite: false,
  },
  {
    id: "3",
    name: "Roulette Live",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "4",
    name: "Lightning Roulette",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "5",
    name: "Dream Catcher",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "6",
    name: "Blackjack Classic",
    provider: "Evolution Gaming",
    image: "/roulette.jpg",
    category: GameCategory.TABLE,
    isFavorite: false,
  },
  {
    id: "7",
    name: "Fire Joker",
    provider: "Play'n GO",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "8",
    name: "Book of Dead",
    provider: "Play'n GO",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "9",
    name: "Immersive Roulette",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "10",
    name: "Reactoonz",
    provider: "Play'n GO",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "11",
    name: "Classic Blackjack Gold",
    provider: "Microgaming",
    image: "/roulette.jpg",
    category: GameCategory.TABLE,
    isFavorite: false,
  },
  {
    id: "12",
    name: "Texas Hold’em Bonus",
    provider: "Evolution Gaming",
    image: "/roulette.jpg",
    category: GameCategory.TABLE,
    isFavorite: false,
  },
  {
    id: "13",
    name: "Baccarat Squeeze",
    provider: "Evolution Gaming",
    image: "/roulette.jpg",
    category: GameCategory.TABLE,
    isFavorite: false,
  },
  {
    id: "14",
    name: "Crazy Time",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "15",
    name: "Jackpot Raiders",
    provider: "Yggdrasil",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "16",
    name: "Fire Joker",
    provider: "Play'n GO",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "17",
    name: "Twin Spin",
    provider: "NetEnt",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "18",
    name: "Divine Fortune",
    provider: "NetEnt",
    image: "/slot.jpg",
    category: GameCategory.SLOTS,
    isFavorite: false,
  },
  {
    id: "19",
    name: "Immersive Blackjack",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  },
  {
    id: "20",
    name: "Roulette Live",
    provider: "Evolution Gaming",
    image: "/live.jpg",
    category: GameCategory.LIVE,
    isFavorite: false,
  }
];
